---
title: "ml_groopwork_eldorado"
author: "Stephan Wernli"
date: "13 April 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rstudioapi::getActiveDocumentContext

library(tidyverse)


url_r <- "https://raw.githubusercontent.com/gunter-trooper/ML-Group-Work/master/Machine-learning-databases/winequality-red.csv"
winequality_red <- read_delim(url_r,";", escape_double = FALSE, trim_ws = TRUE)
names(winequality_red)<-str_replace_all(names(winequality_red), c(" " = "." , "," = "" ))
winequality_red$type <- "red"

url_w <- "https://raw.githubusercontent.com/gunter-trooper/ML-Group-Work/master/Machine-learning-databases/winequality-white.csv"
winequality_white <- read_delim(url_w,";", escape_double = FALSE, trim_ws = TRUE)
names(winequality_white)<-str_replace_all(names(winequality_white), c(" " = "." , "," = "" ))
winequality_white$type <- "white"


winequality <- bind_rows(winequality_red,winequality_white)
winequality$type <- as.factor(winequality$type)
```

## R Markdown



```{r wine1}
winequality %>% summary()
fit <- lm(quality ~ .,data = winequality)
summary(fit)
hist(winequality$quality)
boxplot(winequality$quality ~ winequality$type)
```

## Including Plots

You can also embed plots, for example:

```{r wine2}
library(splines)
lm.regressionSplines <- lm(quality ~ bs(alcohol, df = 3), data = winequality_red)
summary(lm.regressionSplines)
plot(lm.regressionSplines)
```



```{r wine3}
library(mgcv)
gam.1 <- gam(quality ~ s(alcohol) + s(sulphates) + s(pH), data = winequality_red)
summary(gam.1)
plot(gam.1, residuals = TRUE, cex = 2)
```




```{r wine4}
library(ISLR)
library(tree)

wine_tree <-  tree(quality ~ .,data = winequality)

plot(wine_tree)
text(wine_tree, cex=0.75) # cex: set character size to 0.75

summary(wine_tree)
```








